# .goreleaser.yml
# Build customization
builds:
  - binary: release-test
    goos:
      - darwin
      - linux
    goarch:
      - amd64

checksum:
  - name_template: "{{.ProjectName}}"_sha256

dockers:
  - image: magiconair/release-test
