builds:
  -
    binary: release-test
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
checksum:
  name_template: '{{.ProjectName}}-{{.ProjectVersion}}.sha256'
dockers:
  - image: magiconair/release-test
